In [1]:
# import the required libraries
import numpy as np
import pandas as pd


In [2]:
# read the dataset
df = pd.read_csv("D:\mtech\ML\Asssignments\module\Adult.csv")

In [3]:
df.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [5]:
# Drop education as education and education number will convey same meaning and with this we can delete duplicated data
#df.drop(['education'],axis=1)

In [6]:
df["fnlwgt"].value_counts

<bound method IndexOpsMixin.value_counts of 0         77053
1        132870
2        186061
3        140359
4        264663
          ...  
32556    310152
32557    257302
32558    154374
32559    151910
32560    201490
Name: fnlwgt, Length: 32561, dtype: int64>

In [7]:
# remove fnlwgt as it the range of values are very high
df = df.drop(["education","fnlwgt"],axis=1)

In [8]:
# replace '?'' with 'NaN'
df.replace('?',np.NaN,inplace=True)

In [9]:
df

age workclass  education.num      marital.status         occupation  \
0       90       NaN              9             Widowed                NaN   
1       82   Private              9             Widowed    Exec-managerial   
2       66       NaN             10             Widowed                NaN   
3       54   Private              4            Divorced  Machine-op-inspct   
4       41   Private             10           Separated     Prof-specialty   
...    ...       ...            ...                 ...                ...   
32556   22   Private             10       Never-married    Protective-serv   
32557   27   Private             12  Married-civ-spouse       Tech-support   
32558   40   Private              9  Married-civ-spouse  Machine-op-inspct   
32559   58   Private              9             Widowed       Adm-clerical   
32560   22   Private              9       Never-married       Adm-clerical   

        relationship   race     sex  capital.gain  capital.loss  \
0      Not-in-family  White  Female             0          4356   
1      Not-in-family  White  Female             0          4356   
2          Unmarried  Black  Female             0          4356   
3          Unmarried  White  Female             0          3900   
4          Own-child  White  Female             0          3900   
...              ...    ...     ...           ...           ...   
32556  Not-in-family  White    Male             0             0   
32557           Wife  White  Female             0             0   
32558        Husband  White    Male             0             0   
32559      Unmarried  White  Female             0             0   
32560      Own-child  White    Male             0             0   

       hours.per.week native.country income  
0                  40  United-States  <=50K  
1                  18  United-States  <=50K  
2                  40  United-States  <=50K  
3                  40  United-States  <=50K  
4                  40  United-States  <=50K  
...               ...            ...    ...  
32556              40  United-States  <=50K  
32557              38  United-States  <=50K  
32558              40  United-States   >50K  
32559              40  United-States  <=50K  
32560              20  United-States  <=50K  

[32561 rows x 13 columns]

In [10]:
# repalce NaN with forward fill
df.fillna(method='ffill',inplace=True)

In [11]:
df.head()

age workclass  education.num marital.status         occupation  \
0   90       NaN              9        Widowed                NaN   
1   82   Private              9        Widowed    Exec-managerial   
2   66   Private             10        Widowed    Exec-managerial   
3   54   Private              4       Divorced  Machine-op-inspct   
4   41   Private             10      Separated     Prof-specialty   

    relationship   race     sex  capital.gain  capital.loss  hours.per.week  \
0  Not-in-family  White  Female             0          4356              40   
1  Not-in-family  White  Female             0          4356              18   
2      Unmarried  Black  Female             0          4356              40   
3      Unmarried  White  Female             0          3900              40   
4      Own-child  White  Female             0          3900              40   

  native.country income  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4  United-States  <=50K

In [12]:
# Need to fit the data Otherwise while fitting training and testing data we can't compare
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
df['workclass'] = le.fit_transform(df['workclass'].astype(str))
df['marital.status'] = le.fit_transform(df['marital.status'])
df['occupation'] = le.fit_transform(df['occupation'].astype(str))
df['relationship'] = le.fit_transform(df['relationship'])
df['race'] = le.fit_transform(df['race'])
df['sex'] = le.fit_transform(df['sex'])
df['native.country'] = le.fit_transform(df['native.country'])
df['income'] = le.fit_transform(df['income'])

df.head()

age  workclass  education.num  marital.status  occupation  relationship  \
0   90          8              9               6          14             1   
1   82          3              9               6           3             1   
2   66          3             10               6           3             4   
3   54          3              4               0           6             4   
4   41          3             10               5           9             3   

   race  sex  capital.gain  capital.loss  hours.per.week  native.country  \
0     4    0             0          4356              40              38   
1     4    0             0          4356              18              38   
2     2    0             0          4356              40              38   
3     4    0             0          3900              40              38   
4     4    0             0          3900              40              38   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
# replace x with all columns except income
x = df.drop(['income'],axis=1)

In [14]:
# replace y with income column
y = df['income']

In [15]:
#split the data into train and test data
# 30% test data and 70% training data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [16]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
gb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [17]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [18]:
y_pred = gb.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred)*100)

              precision    recall  f1-score   support

           0       0.82      0.95      0.88      7421
           1       0.67      0.32      0.44      2348

    accuracy                           0.80      9769
   macro avg       0.74      0.64      0.66      9769
weighted avg       0.78      0.80      0.77      9769

[[7048  373]
 [1589  759]]
79.91606100931517


In [19]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(x_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [20]:
y_pred = bnb.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred)*100)

              precision    recall  f1-score   support

           0       0.89      0.72      0.79      7421
           1       0.45      0.72      0.55      2348

    accuracy                           0.72      9769
   macro avg       0.67      0.72      0.67      9769
weighted avg       0.78      0.72      0.74      9769

[[5308 2113]
 [ 649 1699]]
71.72689118640598


In [22]:
from sklearn.naive_bayes import MultinomialNB
MnB = MultinomialNB()
MnB.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
y_pred = MnB.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred)*100)

              precision    recall  f1-score   support

           0       0.79      0.96      0.87      7421
           1       0.62      0.21      0.32      2348

    accuracy                           0.78      9769
   macro avg       0.71      0.59      0.59      9769
weighted avg       0.75      0.78      0.74      9769

[[7117  304]
 [1849  499]]
77.96089671409561
