In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
# opening Iris dataset
with open('D:\mtech\ML\Asssignments\module\iris.data','r') as Iris_reader:
    print(Iris_reader.read())


5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.4,3.7,1.5,0.2,Iris-setosa
4.8,3.4,1.6,0.2,Iris-setosa
4.8,3.0,1.4,0.1,Iris-setosa
4.3,3.0,1.1,0.1,Iris-setosa
5.8,4.0,1.2,0.2,Iris-setosa
5.7,4.4,1.5,0.4,Iris-setosa
5.4,3.9,1.3,0.4,Iris-setosa
5.1,3.5,1.4,0.3,Iris-setosa
5.7,3.8,1.7,0.3,Iris-setosa
5.1,3.8,1.5,0.3,Iris-setosa
5.4,3.4,1.7,0.2,Iris-setosa
5.1,3.7,1.5,0.4,Iris-setosa
4.6,3.6,1.0,0.2,Iris-setosa
5.1,3.3,1.7,0.5,Iris-setosa
4.8,3.4,1.9,0.2,Iris-setosa
5.0,3.0,1.6,0.2,Iris-setosa
5.0,3.4,1.6,0.4,Iris-setosa
5.2,3.5,1.5,0.2,Iris-setosa
5.2,3.4,1.4,0.2,Iris-setosa
4.7,3.2,1.6,0.2,Iris-setosa
4.8,3.1,1.6,0.2,Iris-setosa
5.4,3.4,1.5,0.4,Iris-setosa
5.2,4.1,1.5,0.1,Iris-setosa
5.5,4.2,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.0,3.2,1.2,0.2,Iris

In [3]:
# opening names dataset
with open('D:\mtech\ML\Asssignments\module\iris.names','r') as Iris_names:
    Iris_names.read()

In [4]:
# opening with pandas
pd_iris = pd.read_csv('D:\mtech\ML\Asssignments\module\iris.data',header=None,names=["Sepel Length","Sepal Width","Petal Length","Petal Width","Class"])
pd_iris.head()

Sepel Length  Sepal Width  Petal Length  Petal Width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()
pd_iris["Class"] = ord_enc.fit_transform(pd_iris[["Class"]])

In [6]:
# finding the missing values using isnull() of pandas
pd_no_null = pd.isnull(pd_iris)

In [7]:
print(pd_iris)

     Sepel Length  Sepal Width  Petal Length  Petal Width  Class
0             5.1          3.5           1.4          0.2    0.0
1             4.9          3.0           1.4          0.2    0.0
2             4.7          3.2           1.3          0.2    0.0
3             4.6          3.1           1.5          0.2    0.0
4             5.0          3.6           1.4          0.2    0.0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3    2.0
146           6.3          2.5           5.0          1.9    2.0
147           6.5          3.0           5.2          2.0    2.0
148           6.2          3.4           5.4          2.3    2.0
149           5.9          3.0           5.1          1.8    2.0

[150 rows x 5 columns]


In [8]:
pd_iris.fillna(value=pd_iris.mean(),inplace=True)

In [9]:
print(pd_iris)

     Sepel Length  Sepal Width  Petal Length  Petal Width  Class
0             5.1          3.5           1.4          0.2    0.0
1             4.9          3.0           1.4          0.2    0.0
2             4.7          3.2           1.3          0.2    0.0
3             4.6          3.1           1.5          0.2    0.0
4             5.0          3.6           1.4          0.2    0.0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3    2.0
146           6.3          2.5           5.0          1.9    2.0
147           6.5          3.0           5.2          2.0    2.0
148           6.2          3.4           5.4          2.3    2.0
149           5.9          3.0           5.1          1.8    2.0

[150 rows x 5 columns]


In [10]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
pd_iris['Sepel Length'] = le.fit_transform(pd_iris['Sepel Length'])
pd_iris['Sepal Width'] = le.fit_transform(pd_iris['Sepal Width'])
pd_iris['Petal Length'] = le.fit_transform(pd_iris['Petal Length'])
pd_iris['Petal Width'] = le.fit_transform(pd_iris['Petal Width'])
pd_iris['Class'] = le.fit_transform(pd_iris['Class'])

pd_iris.head()

Sepel Length  Sepal Width  Petal Length  Petal Width  Class
0             8           14             4            1      0
1             6            9             4            1      0
2             4           11             3            1      0
3             3           10             5            1      0
4             7           15             4            1      0

In [11]:
Y = pd_iris.iloc[:,-1:]

In [12]:
X = pd_iris.iloc[:,:-1]

In [13]:
print(Y)

     Class
0        0
1        0
2        0
3        0
4        0
..     ...
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]


In [14]:
from sklearn.model_selection import train_test_split
train_X,test_X = train_test_split(X,test_size=0.3)

In [15]:
train_Y,test_Y = train_test_split(Y,test_size=0.3)

In [16]:
Y.shape

(150, 1)

In [17]:
#Y = np.ravel(Y,order='F')
Y

Class
0        0
1        0
2        0
3        0
4        0
..     ...
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

train_X, test_X, train_Y, test_Y = train_test_split(X,Y,test_size=0.3)
log_reg = LogisticRegression()
log_reg.fit(train_X,np.ravel(train_Y,order='C'))

C:\Users\jayad\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [23]:
y_pred = log_reg.predict(test_X)
print(classification_report(test_Y,y_pred))
print(confusion_matrix(test_Y,y_pred))
print(accuracy_score(test_Y,y_pred)*100)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.87      1.00      0.93        13
           2       1.00      0.86      0.92        14

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

[[18  0  0]
 [ 0 13  0]
 [ 0  2 12]]
95.55555555555556


In [31]:
final_output=pd.DataFrame({'Actual':test_Y['Class'].tolist(),'Predicted':y_pred})

In [32]:
final_output.to_csv('D:\mtech\ML\Asssignments\module\output.csv',index=False)